language: c
addons:
  apt:
    packages:
    - git
    - build-essential
    - fakeroot
    - kernel-package
    - zlib1g-dev
    - libncurses5-dev
    - lzop
    - gcc-arm-linux-gnueabihf
    - binutils-arm-linux-gnueabihf
    - bc
env:
  global:
  - ARCH=arm
  - CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf-
  - INSTALL_MOD_PATH=/tmp/kernel
  - KBUILD_DEBARCH=armhf
  - CONFIG_PLATFORM_ARM_SUNxI=y
script:
- make
deploy:
  provider: bintray
  file: ".travis.bintray.json"
  user: brimstone
  key: $BINTRAY_API_KEY
